/*
 * Generates a contract test from the client, so the two cannot drift.
 *
 * The SQL tests prove the rules hold. They do not prove the app is asking for
 * things that exist. A column renamed in schema.sql, or an RPC argument called
 * p_hangout on one side and p_hangout_id on the other, type-checks perfectly
 * and then fails at runtime the first time a real Supabase project is connected.
 * That is the worst place to find it.
 *
 * So rather than hand-maintaining a list that goes stale, this reads the actual
 * client source, extracts every table, column, embedded relationship, filter and
 * RPC argument it depends on, and emits SQL that asserts each one exists in the
 * database. Run by scripts/test-db.sh against the real schema.
 *
 *   node scripts/contract.mjs > supabase/test/contract.generated.sql
 */
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SOURCES = ['src/data/supabaseStore.ts', 'src/data/shareApi.ts']

const source = SOURCES.map((f) => readFileSync(join(ROOT, f), 'utf8')).join('\n')

/** Splits "a, b(c, d), e" on commas that are not inside parentheses. */
function splitTop(s) {
  const out = []
  let depth = 0
  let current = ''
  for (const ch of s) {
    if (ch === '(') depth++
    if (ch === ')') depth--
    if (ch === ',' && depth === 0) { out.push(current.trim()); current = '' } else current += ch
  }
  if (current.trim()) out.push(current.trim())
  return out
}

const tables = new Set()
const columns = new Set()   // "table.column"
const embeds = new Set()    // "parent>child"
const rpcs = new Map()      // fn -> Set(argNames)
const loose = new Set()     // snake_case names read off result rows

/** A select string, which may nest: "*, members(user_id), slots(*, votes(user_id))". */
function walkSelect(table, select) {
  tables.add(table)
  for (const part of splitTop(select)) {
    const nested = part.match(/^([a-z_][a-z0-9_]*)\s*\((.*)\)$/s)
    if (nested) {
      embeds.add(`${table}>${nested[1]}`)
      walkSelect(nested[1], nested[2])
    } else if (part !== '*') {
      columns.add(`${table}.${part.trim()}`)
    }
  }
}

// Each .from('x') starts a chain; read the methods that follow it.
const fromRe = /\.from\('([a-z_]+)'\)/g
let m
while ((m = fromRe.exec(source))) {
  const table = m[1]
  tables.add(table)
  const rest = source.slice(m.index + m[0].length)
  // The chain ends at the next .from( or .rpc(, whichever comes first.
  const end = Math.min(
    ...[rest.indexOf('.from('), rest.indexOf('.rpc('), 600].filter((n) => n >= 0),
  )
  const chain = rest.slice(0, end)

  const sel = chain.match(/\.select\(\s*'([^']*)'/)
  if (sel) walkSelect(table, sel[1])

  for (const w of chain.matchAll(/\.(insert|update)\(\s*\{([^}]*)\}/g)) {
    for (const key of w[2].matchAll(/(?:^|[,{\s])([a-z_][a-z0-9_]*)\s*:/g)) columns.add(`${table}.${key[1]}`)
    // `{ ...this.planFields(input), done_count: 1 }` hides keys behind a helper.
    for (const spread of w[2].matchAll(/\.\.\.this\.(\w+)\(/g)) {
      const body = source.match(new RegExp(`${spread[1]}\\([^)]*\\)\\s*\\{[\\s\\S]*?return \\{([\\s\\S]*?)\\n\\s*\\}`))
      if (body) for (const key of body[1].matchAll(/(?:^|[,\s])([a-z_][a-z0-9_]*)\s*:/g)) columns.add(`${table}.${key[1]}`)
    }
  }
  for (const f of chain.matchAll(/\.(?:eq|neq|gt|lt|gte|lte|in|order)\(\s*'([a-z_][a-z0-9_]*)'/g)) {
    columns.add(`${table}.${f[1]}`)
  }
}

for (const r of source.matchAll(/\.rpc\(\s*'([a-z_]+)'\s*,\s*\{([^}]*)\}/g)) {
  const args = new Set()
  for (const key of r[2].matchAll(/(?:^|[,{\s])([a-z_][a-z0-9_]*)\s*:/g)) args.add(key[1])
  rpcs.set(r[1], new Set([...(rpcs.get(r[1]) ?? []), ...args]))
}
// `this.rpc('name', { ... })` goes through a wrapper, so catch that shape too.
for (const r of source.matchAll(/this\.rpc\(\s*'([a-z_]+)'\s*,\s*\{([^}]*)\}/g)) {
  const args = new Set()
  for (const key of r[2].matchAll(/(?:^|[,{\s])([a-z_][a-z0-9_]*)\s*:/g)) args.add(key[1])
  rpcs.set(r[1], new Set([...(rpcs.get(r[1]) ?? []), ...args]))
}

// Snake_case properties read off a result row are database names by definition;
// camelCase ones are ours. This catches a typo in the mapping that TypeScript
// cannot, because the rows are untyped.
for (const p of source.matchAll(/\b[A-Za-z_$][\w$]*\.([a-z]+(?:_[a-z0-9]+)+)\b/g)) loose.add(p[1])

if (tables.size === 0 || rpcs.size === 0) {
  console.error('contract: parsed nothing, the client source must have changed shape')
  process.exit(1)
}

const lit = (s) => `'${s.replace(/'/g, "''")}'`
const out = []
out.push(`-- GENERATED by scripts/contract.mjs from ${SOURCES.join(' and ')}. Do not edit.`)
out.push('--')
out.push('-- Asserts that everything the client asks the database for actually exists:')
out.push('-- tables, columns, embedded relationships, filters and RPC argument names.')
out.push('-- A rename on either side fails here instead of at runtime on first connect.')
out.push('')
out.push('\\set ON_ERROR_STOP on')
out.push('\\o /dev/null')
out.push('set client_min_messages to notice;')
out.push('')
out.push(`\\qecho ''`)
out.push(`\\qecho 'client contract (generated from the app source)'`)
out.push('')

for (const t of [...tables].sort()) {
  out.push(
    `select assert((select count(*) from information_schema.tables where table_schema='public' and table_name=${lit(t)}) = 1,` +
      ` 'table ${t} exists');`,
  )
}

for (const c of [...columns].sort()) {
  const [t, col] = c.split('.')
  out.push(
    `select assert((select count(*) from information_schema.columns where table_schema='public' and table_name=${lit(t)} and column_name=${lit(col)}) = 1,` +
      ` 'the client reads or writes ${t}.${col}');`,
  )
}

// PostgREST resolves an embedded resource through a foreign key. Exactly one
// path must exist: none and the embed 404s, several and it refuses as ambiguous.
for (const e of [...embeds].sort()) {
  const [parent, child] = e.split('>')
  out.push(
    `select assert((
       select count(*) from pg_constraint c
       where c.contype = 'f'
         and ((c.conrelid = ${lit(child)}::regclass and c.confrelid = ${lit(parent)}::regclass)
           or (c.conrelid = ${lit(parent)}::regclass and c.confrelid = ${lit(child)}::regclass))
     ) = 1, 'exactly one foreign key joins ${parent} to ${child}, so the embed resolves');`,
  )
}

for (const [fn, args] of [...rpcs].sort()) {
  const list = [...args].sort()
  out.push(
    `select assert((select count(*) from pg_proc p join pg_namespace n on n.oid = p.pronamespace` +
      ` where n.nspname='public' and p.proname=${lit(fn)}) = 1, 'the function ${fn} exists');`,
  )
  if (list.length) {
    out.push(
      `select assert((select coalesce(p.proargnames, '{}') @> array[${list.map(lit).join(', ')}]::text[]` +
        ` from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname='public' and p.proname=${lit(fn)}),` +
        ` '${fn} takes the arguments the client sends: ${list.join(', ')}');`,
    )
  }
}

// These are read off untyped rows, so nothing else would catch a typo. A name
// is legitimate if it is a column, a table (an embedded relationship is read by
// its table name), or an output column of a table-returning function such as
// get_share, which is where `shared_by` comes from.
const known = [...loose].sort()
out.push(
  `select assert((
     select coalesce(string_agg(name, ', ' order by name), '')
     from unnest(array[${known.map(lit).join(', ')}]::text[]) name
     where not exists (select 1 from information_schema.columns where table_schema in ('public','auth') and column_name = name)
       and not exists (select 1 from information_schema.tables where table_schema='public' and table_name = name)
       and not exists (
         select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
         where n.nspname = 'public' and name = any(p.proargnames)
       )
   ) = '', 'every field the client reads off a row is a real column, table or function output');`,
)

out.push('')
out.push(`\\qecho 'the client and the schema agree'`)
out.push('\\o')
out.push('')

console.log(out.join('\n'))
console.error(
  `contract: ${tables.size} tables, ${columns.size} columns, ${embeds.size} embeds, ${rpcs.size} functions, ${loose.size} row fields`,
)
